### ISSUE TITLE
1.3.1 connect to running Registry throws MalformedRequestException (POST instead of PUT)

### ISSUE THREAD

**Issue by hmrc87** [eclipse-basyx/basyx-java-sdk#235]
Hi, 
I am using Version 1.3.1 of the Registry and the SDK and trying to achieve the following:

I want to connect to a OTS Registry that is running in Docker eclipsebasyx/aas-registry:1.3.1

When I try to connect to it via
`var registry = new AASRegistryProxy("http://localhost:8082/registry/api/v1/registry");`
it returns: 

```
Exception in thread "main" org.eclipse.basyx.vab.exception.provider.MalformedRequestException: [6 | 400 - MalformedRequestException: Create (POST) on a registry is not supported. Please, use put, 6 | [HTTP POST] Failed to request http://localhost:8082/registry with mediatype application/json;charset=UTF-8. "MalformedRequestException: Create (POST) on a registry is not supported. Please, use put"]
	at org.eclipse.basyx.vab.protocol.http.server.ExceptionToHTTPCodeMapper.mapToException(ExceptionToHTTPCodeMapper.java:100)
	at org.eclipse.basyx.vab.protocol.http.connector.HTTPConnector.handleProcessingException(HTTPConnector.java:325)
	at org.eclipse.basyx.vab.protocol.http.connector.HTTPConnector.httpPost(HTTPConnector.java:269)
	at org.eclipse.basyx.vab.protocol.http.connector.HTTPConnector.createValue(HTTPConnector.java:142)
	at org.eclipse.basyx.vab.coder.json.connector.JSONConnector.createValue(JSONConnector.java:141)
	at org.eclipse.basyx.vab.modelprovider.VABElementProxy.createValue(VABElementProxy.java:114)
	at org.eclipse.basyx.vab.registry.proxy.VABRegistryProxy.addMapping(VABRegistryProxy.java:77)
	at de.xyz.basyx.experiments.localserverwithgateway.Main.main(Main.java:37)

```

However when I create the Registry in Memory directly in my program it works with using the AASRegistryProxy.

**Comment by FrankSchnicke** [comment]
Hi,
thanks for sharing the stack trace.

For interacting with the AAS Registry by using the AASRegistryProxy, please only use the methods of the IAASRegistry interface. The addMapping method is coming from the VABRegistryProxy and only exists for legacy reasons. I think the method you're looking for is "register".

**Comment by hmrc87** [comment]
Right, now I see it. Thanks! I found it in an older example showing how the Gateway-Communication works!

**Comment by hmrc87** [comment]
by the way: I took the test at basyx/testsuite/regression/vab/gateway/TestGateway.java for inspiration
