### ISSUE TITLE
BaSyx SDK incompatible with Spring Boot due to Tomcat Version mismatch

### ISSUE THREAD

**Issue by Marrrrtthias** [eclipse-basyx/basyx-java-sdk#77]
Hi, 
as I am implementing an application in Spring Boot that relies on the BaSyx java SDK I came upon a problem with the Apache Tomcat dependency used by the BaSyx SDK. Calling `RegistryComponent.startComponent()` or `AASServerComponent.startComponent()` produces an exception preventing the user from starting an AAS server or registry. 

```
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[d2e61a47-5324-4448-8c8f-a0cca4e2fb72]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.eclipse.basyx.vab.protocol.http.server.BaSyxHTTPServer.lambda$start$0(BaSyxHTTPServer.java:161) ~[basyx.sdk-1.0.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.scheduleWithFixedDelay(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)" because the return value of "org.apache.catalina.Server.getUtilityExecutor()" is null
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:951) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	... 7 common frames omitted
```

## Steps to reproduce
I created a minimal example to demonstrate the problem:

1. Use Spring initializr https://start.spring.io/ to create a new project
2. Add the Spring web dependency (uses tomcat-embed-core-9.0.60)
3. generate the project and add the BaSyx SDK to its dependecies
4. create a controller that uses the SDK to start an AAS registry
```java
@Controller
public class ServerController {

    @PostConstruct
    void init() {
        // assemble paths of AAS Server and Registry
        int registryPort = 4000;
        String registryContextPath = "registry";

        //create RegistryComponent
        BaSyxContextConfiguration registryContextConfig = new BaSyxContextConfiguration(registryPort, registryContextPath);
        BaSyxRegistryConfiguration registryConfig = new BaSyxRegistryConfiguration(RegistryBackend.INMEMORY);
        RegistryComponent registry = new RegistryComponent(registryContextConfig, registryConfig);

        registry.startComponent();
    }

}
```

I also created a project that contains the code to demonstrate the problem: https://github.com/Marrrrtthias/basyx-dependency-problem

## Investigation

To me it seems like the problem comes up because a dependency mismatch between Spring-web which uses tomcat-embed-core 9.0.62 and basyx.sdk which uses tomcat-catalina 8.5.41, both of which provide the classes Tomcat.java, LifecycleBase.java and others. Because Maven can not handle different versions of the same library in ine project the BaSyx SDK uses the classes from tomcat-embed-core 9.0.62 which are apparenly incompatible.

I am not sure if this is really a BaSyx problem or if you can really do anything about it, but because Spring is a very widely used library i wanted to report the problem nonetheless.

**Comment by FrankSchnicke** [comment]
Many thanks for pointing this out. We will take a look and see if we can easily upgrade to Tomcat 9. I will update this ticket when the upgrade is done.

**Comment by AbiGithub91** [comment]
I am also facing the same issue.

**Comment by mdanish98** [comment]
Hi Marrrrtthias, 

The PR #93 will address the issue raised here.

However, as you said that dependency mismatch between Spring-web which uses tomcat-embed-core 9.0.62 and basyx.sdk which uses tomcat-catalina 8.5.41, this is right. But we can easily exclude **"spring-boot-starter-tomcat"** from **springframework** dependency. 

It means that we are explicitly instructing to not use Tomcat server from springframework package, then it will use the Tomcat version defined in the Basyx SDK and the issue will not occur.
I have excluded  **"spring-boot-starter-tomcat"** from your provided basyx-dependency-problem project and the Tomcat server defined in Basyx SDK i.e 8.5.41 is getting executed and not the 9.0.62 defined in Springframework. 
Following are the logs : 

`2022-06-26 15:53:32.619  INFO 16604 --- [           main] c.e.d.DependecyProblemApplicationTests   : Starting DependecyProblemApplicationTests using Java 1.8.0_202 on lap552 with PID 16604 (started by danish in C:\Users\danish\eclipse-workspace\basyx-dependency-problem)
2022-06-26 15:53:32.621  INFO 16604 --- [           main] c.e.d.DependecyProblemApplicationTests   : No active profile set, falling back to 1 default profile: "default"
2022-06-26 15:53:33.934  INFO 16604 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2022-06-26 15:53:33.965  INFO 16604 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 MongoDB repository interfaces.
2022-06-26 15:53:34.585  INFO 16604 --- [           main] o.e.b.c.registry.RegistryComponent       : Creating InMemoryRegistry
2022-06-26 15:53:36.356  WARN 16604 --- [           main] o.apache.catalina.core.StandardContext   : A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [registry] does not meet these criteria and has been changed to [/registry]
2022-06-26 15:53:36.836  INFO 16604 --- [       Thread-2] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-06-26 15:53:36.836  INFO 16604 --- [       Thread-2] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.41
2022-06-26 15:53:37.233  INFO 16604 --- [           main] o.e.b.c.registry.RegistryComponent       : Registry server started
2022-06-26 15:53:38.831  INFO 16604 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2022-06-26 15:53:39.050  INFO 16604 --- [localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:23}] to localhost:27017
2022-06-26 15:53:39.050  INFO 16604 --- [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=71426200}
2022-06-26 15:53:39.055  INFO 16604 --- [localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:24}] to localhost:27017
2022-06-26 15:53:39.179  WARN 16604 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2022-06-26 15:53:39.336  WARN 16604 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2022-06-26 15:53:40.051  INFO 16604 --- [           main] c.e.d.DependecyProblemApplicationTests   : Started DependecyProblemApplicationTests in 7.933 seconds (JVM running for 10.156)
[INFO] [1;32mTests run: [0;1;32m1[m, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.348 s - in com.example.dependecyproblem.[1mDependecyProblemApplicationTests`

Also when using the Tomcat updated version 9.0.64 in BaSyx SDK you will see that it is still using 9.0.62 version which is defined in  **"spring-boot-starter-tomcat"** , so if needed exclude tomcat from Spring to avoid such error.

Following lines you have to add to exclude Tomcat from Springframework : 
`<exclusions>
		            <exclusion>
		                <groupId>org.springframework.boot</groupId>
		                <artifactId>spring-boot-starter-tomcat</artifactId>
		            </exclusion>
        		</exclusions>`
